/* In the name of God, the Merciful, the Compassionate */

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using SQLTriage.Data;
using SQLTriage.Tests.Build;
using Xunit;
using Xunit.Abstractions;

namespace SQLTriage.Tests;

/// <summary>
/// THE INVARIANT: <b>the set of routable pages in a build is EXACTLY the union of the route groups
/// whose owning module is compiled into that build.</b> A route present that no compiled module owns,
/// a route absent that a compiled module owns, and a route that no module owns at all each FAIL.
///
/// <para><b>WHY THIS EXISTS.</b> On 2026-09-14 a routable page, <c>/live</c>
/// (<c>Components/Dashboards/LiveDashboard.razor</c>), was found in the COMMUNITY (free) build.
/// <c>buildprofile.targets</c> decides which pages ship in each profile from a hand-maintained list of
/// Content Removes, and nothing derived from the code could notice that escape, or the next one. This
/// is the IP boundary between the free and the paid product.</para>
///
/// <para><b>WHAT "ROUTABLE" MEANS HERE.</b> A <c>Microsoft.AspNetCore.Components.RouteAttribute</c> in
/// the custom-attribute METADATA of a type in the LOADED PRODUCT ASSEMBLY, read with
/// <c>GetCustomAttributesData()</c> so no attribute is ever instantiated. Never a string search: a
/// byte search for <c>/live</c> also hits the community DLL wherever <c>/dashboard/live</c> appears
/// (nine hits when measured on 2026-09-14; the number moves with the build and nothing here asserts
/// it), and <c>Data/RouteConstants.cs</c> declares <c>Sessions = "/sessions"</c> unfenced by
/// design, so <c>/sessions</c> has a byte hit in a build where it is NOT a route (both PROVED
/// 2026-09-14). The specimen controls below hold the census to that distinction.</para>
///
/// <para><b>WHAT "COMPILED IN" MEANS HERE.</b> The product assembly's OWN <see cref="BuildModules"/>
/// constants, read off the loaded assembly by reflection (<c>FieldInfo.GetRawConstantValue()</c>).
/// Never a <c>#if</c> in this project: a symbol answers about the TEST project's compilation, and the
/// question is about the assembly under test. The values this project inlined at compile time are
/// compared with the reflected ones, and a disagreement fails (the stale <c>bin/</c> trap).</para>
///
/// <para><b>PROVENANCE OF THE APPROVED TABLE.</b> <see cref="ApprovedRouteTable"/> was generated by
/// script, not typed, from a route-to-module table derived STRUCTURALLY from the
/// <c>buildprofile.targets</c> XML item tree plus the <c>@page</c> literals, measured at
/// <c>18f5171958c87ebae90d6e18788534b53f8f4c65</c> on 2026-09-17 by lane
/// <c>page-route-profile-census</c>; evidence is filed in the project's private evidence archive at
/// <c>evidence/page-route-profile-census-2026-09-17/</c>. At that commit its Core group equalled the
/// route set of a real community build exactly, so the XML model was faithful. ONE ruling was applied
/// on top of the measurement: <c>/live</c> moves from Core to LiveMonitoring. The result is 91 routes:
/// Core 42, Premium 8, DevTools 10, Portal 3, Operations 11, LiveMonitoring 16, PerfReport 1. Those
/// counts are recorded here as provenance and are deliberately NOT asserted: every verdict in this
/// class compares SETS.</para>
///
/// <para><b>OWNERSHIP IS A RULING, NOT AN INFERENCE.</b> Which edition sells a page is a commercial
/// decision. When a fact here fails, the failure text names what to CHECK; it never names an edit,
/// because the attractive repair (move the route into whichever group makes the test pass) is exactly
/// how the boundary would be moved without anyone deciding to move it.</para>
///
/// <para><b>WHO RUNS THIS.</b> The automatic runner is CI, which builds and tests the COMMUNITY profile
/// on pushes to main and on pull requests (.github/workflows/build.yml; a push to a lane branch alone
/// runs nothing), so the community mode is the one that fires unattended. The full-profile mode is
/// what a developer runs locally; <see cref="F5_a_full_build_predicts_the_community_route_set_the_table_approves"/>
/// exists so that a page escaping community is also caught there.</para>
///
/// <para><b>IT FAILS; IT NEVER SKIPS.</b> A module combination with no frozen expectation is refused
/// with a failure, never skipped: a skipped test renders like a passing one.</para>
/// </summary>
public sealed class RouteProfileCensusTests
{
    private readonly ITestOutputHelper _out;

    public RouteProfileCensusTests(ITestOutputHelper output) => _out = output;

    private const string RouteAttributeFullName = "Microsoft.AspNetCore.Components.RouteAttribute";
    private const string CoreGroup = "Core";

    /// <summary>The product assembly, named by a type it owns.</summary>
    private static Assembly Product => typeof(BuildModules).Assembly;

    /// <summary>The seven <see cref="BuildModules"/> constants, in declaration order.</summary>
    private static readonly string[] ModuleFlagNames =
        { "Community", "Premium", "DevTools", "Portal", "Operations", "LiveMonitoring", "PerfReport" };

    /// <summary>Every group the approved table may use: Core (compiled into every build) plus each
    /// module flag except Community, which is a profile marker and owns no pages.</summary>
    private static readonly string[] RouteGroups =
        { CoreGroup, "Premium", "DevTools", "Portal", "Operations", "LiveMonitoring", "PerfReport" };

    /// <summary>
    /// THE APPROVED ROUTE TABLE: route template, owning group, declaring <c>.razor</c> file. GENERATED
    /// by script from the structural measurement described in the class header, with the one
    /// <c>/live</c> ruling applied. See the header for provenance.
    /// </summary>
    private static readonly (string Route, string Group, string File)[] ApprovedRouteTable =
    {
        // Core
        ("/",                            "Core",            "Pages/Index.razor"),
        ("/about",                       "Core",            "Pages/About.razor"),
        ("/app-metrics",                 "Core",            "Pages/AppMetrics.razor"),
        ("/audit",                       "Core",            "Pages/QuickCheck.razor"),
        ("/audit-log",                   "Core",            "Pages/AuditLogViewer.razor"),
        ("/benchmark",                   "Core",            "Pages/Benchmark.razor"),
        ("/blitz",                       "Core",            "Pages/BlitzDashboard.razor"),
        ("/blocking-forensics",          "Core",            "Pages/BlockingForensics.razor"),
        ("/bpcheck",                     "Core",            "Pages/Bpcheck.razor"),
        ("/capacity",                    "Core",            "Pages/CapacityPlanning.razor"),
        ("/change-ledger",               "Core",            "Pages/ChangeLedger.razor"),
        ("/changed-objects",             "Core",            "Pages/ChangedObjects.razor"),
        ("/checks",                      "Core",            "Pages/Checks.razor"),
        ("/checks/trend/{CheckId}",      "Core",            "Pages/CheckTrend.razor"),
        ("/cio",                         "Core",            "Pages/CioDashboard.razor"),
        ("/code-hotspots",               "Core",            "Pages/CodeHotspots.razor"),
        ("/compare",                     "Core",            "Pages/ServerComparison.razor"),
        ("/compliance-board",            "Core",            "Pages/ComplianceBoard.razor"),
        ("/compliance-map",              "Core",            "Pages/ComplianceMap.razor"),
        ("/compliance-tree",             "Core",            "Pages/ComplianceTree.razor"),
        ("/config-diff",                 "Core",            "Pages/ServerConfigDiff.razor"),
        ("/dba",                         "Core",            "Pages/DbaDashboard.razor"),
        ("/dbatools",                    "Core",            "Pages/DbaTools.razor"),
        ("/diagnostics-roadmap",         "Core",            "Pages/DiagnosticsRoadmap.razor"),
        ("/disk-io",                     "Core",            "Pages/DiskIo.razor"),
        ("/documentation",               "Core",            "Pages/Documentation.razor"),
        ("/fullaudit",                   "Core",            "Pages/FullAudit.razor"),
        ("/governance",                  "Core",            "Pages/Governance.razor"),
        ("/guide",                       "Core",            "Pages/Guide.razor"),
        ("/health",                      "Core",            "Pages/Health.razor"),
        ("/index-analysis",              "Core",            "Pages/IndexAnalysis.razor"),
        ("/installation-helper",         "Core",            "Pages/InstallationHelper.razor"),
        ("/login",                       "Core",            "Pages/Login.razor"),
        ("/maintenance-recommendations", "Core",            "Pages/MaintenanceRecommendations.razor"),
        ("/onboarding",                  "Core",            "Pages/Onboarding.razor"),
        ("/playbooks",                   "Core",            "Pages/Playbooks.razor"),
        ("/reports",                     "Core",            "Pages/ReportBundles.razor"),
        ("/server-docs",                 "Core",            "Pages/ServerDocs.razor"),
        ("/servers",                     "Core",            "Pages/Servers.razor"),
        ("/servers/baseline",            "Core",            "Pages/BaselineProgress.razor"),
        ("/settings",                    "Core",            "Pages/Settings.razor"),
        ("/vulnerabilityassessment",     "Core",            "Pages/VulnerabilityAssessment.razor"),
        // Premium
        ("/advanced-reporting",          "Premium",         "Pages/AdvancedReporting.razor"),
        ("/agent-job-guard",             "Premium",         "Pages/AgentJobGuard.razor"),
        ("/agent-job-sync",              "Premium",         "Pages/AgentJobSync.razor"),
        ("/bestpractice",                "Premium",         "Pages/BestPractice.razor"),
        ("/consolidation",               "Premium",         "Pages/CapacityConsolidation.razor"),
        ("/premium",                     "Premium",         "Pages/Premium.razor"),
        ("/remediation",                 "Premium",         "Pages/Remediation.razor"),
        ("/server-configuration",        "Premium",         "Pages/ServerConfiguration.razor"),
        // DevTools
        ("/access-surface",              "DevTools",        "Pages/AccessSurface.razor"),
        ("/build-profile",               "DevTools",        "Pages/BuildProfile.razor"),
        ("/check-validator",             "DevTools",        "Pages/CheckValidator.razor"),
        ("/import-results",              "DevTools",        "Pages/ImportResults.razor"),
        ("/offboarding-trace",           "DevTools",        "Pages/OffboardingTrace.razor"),
        ("/remediation-lab",             "DevTools",        "Pages/RemediationLab.razor"),
        ("/remediation-tuner",           "DevTools",        "Pages/RemediationTuner.razor"),
        ("/riskreport",                  "DevTools",        "Pages/RiskReport.razor"),
        ("/sod-matrix",                  "DevTools",        "Pages/SodMatrix.razor"),
        ("/test-plan",                   "DevTools",        "Pages/TestPlan.razor"),
        // Portal
        ("/export-pack",                 "Portal",          "Pages/Portal/ExportPack.razor"),
        ("/portal-publish",              "Portal",          "Pages/Portal/PublishToPortal.razor"),
        ("/portal-status",               "Portal",          "Pages/Portal/PortalStatus.razor"),
        // Operations
        ("/agent-timeline",              "Operations",      "Pages/AgentJobTimeline.razor"),
        ("/alerting-config",             "Operations",      "Pages/AlertingConfig.razor"),
        ("/alerts",                      "Operations",      "Pages/Alerts.razor"),
        ("/alerts-noc",                  "Operations",      "Pages/AlertsNoc.razor"),
        ("/editauditscripts",            "Operations",      "Pages/EditAuditScripts.razor"),
        ("/environment",                 "Operations",      "Pages/EnvironmentView.razor"),
        ("/query",                       "Operations",      "Pages/QueryExecutor.razor"),
        ("/replication-map",             "Operations",      "Pages/ReplicationMap.razor"),
        ("/scheduled-tasks",             "Operations",      "Pages/ScheduledTasks.razor"),
        ("/service-management",          "Operations",      "Pages/ServiceManagement.razor"),
        ("/services",                    "Operations",      "Pages/Services.razor"),
        // LiveMonitoring
        ("/dashboard/sessions",          "LiveMonitoring",  "Pages/Sessions.razor"),
        ("/dashboard/{DashboardId}",     "LiveMonitoring",  "Pages/Dashboard.razor"),
        ("/instance",                    "LiveMonitoring",  "Pages/InstanceOverview.razor"),
        ("/live",                        "LiveMonitoring",  "Components/Dashboards/LiveDashboard.razor"),
        ("/longqueries",                 "LiveMonitoring",  "Pages/LongQueries.razor"),
        ("/memory",                      "LiveMonitoring",  "Pages/Pmemory.razor"),
        ("/pevents",                     "LiveMonitoring",  "Pages/Pevents.razor"),
        ("/pmemory",                     "LiveMonitoring",  "Pages/Pmemory.razor"),
        ("/pmemory-analysis",            "LiveMonitoring",  "Pages/PmemoryAnalysis.razor"),
        ("/pquery",                      "LiveMonitoring",  "Pages/Pquery.razor"),
        ("/querystore",                  "LiveMonitoring",  "Pages/QueryStore.razor"),
        ("/scheduler-health",            "LiveMonitoring",  "Pages/SchedulerHealth.razor"),
        ("/sessions",                    "LiveMonitoring",  "Pages/Sessions.razor"),
        ("/trends",                      "LiveMonitoring",  "Pages/PerformanceTrends.razor"),
        ("/waitevents",                  "LiveMonitoring",  "Pages/WaitEvents.razor"),
        ("/xevents",                     "LiveMonitoring",  "Pages/XEvents.razor"),
        // PerfReport
        ("/performance-report",          "PerfReport",      "Pages/PerformanceReport.razor"),
    };

    // ── The instrument ─────────────────────────────────────────────────────────────────────────

    private sealed record RouteRow(string Route, string TypeName);

    private sealed record RouteCensus(
        string AssemblySimpleName,
        string AssemblyVersion,
        int TypeCount,
        IReadOnlyList<string> TypeLoadFailures,
        IReadOnlyList<string> AttributeReadFailures,
        IReadOnlyList<string> ForeignRouteAttributes,
        IReadOnlyList<RouteRow> Rows);

    private static readonly Lazy<RouteCensus> Census = new(ReadRouteCensus);

    /// <summary>
    /// Enumerates every route template from RouteAttribute METADATA on the product assembly's types.
    /// Nothing is instantiated and no app code runs. A type that cannot be loaded, or whose attribute
    /// data cannot be read, is RECORDED rather than skipped, because an unreadable type is invisible to
    /// every verdict below and would read as a pass.
    /// </summary>
    private static RouteCensus ReadRouteCensus()
    {
        var product = Product;
        var typeLoadFailures = new List<string>();
        Type?[] types;
        try
        {
            types = product.GetTypes();
        }
        catch (ReflectionTypeLoadException ex)
        {
            types = ex.Types;
            foreach (var loaderException in ex.LoaderExceptions)
                if (loaderException != null)
                    typeLoadFailures.Add(loaderException.GetType().Name + ": " + loaderException.Message);
            var unloaded = types.Count(t => t == null);
            typeLoadFailures.Add(unloaded + " type(s) could not be loaded (ReflectionTypeLoadException)");
        }

        var attributeReadFailures = new List<string>();
        var foreign = new List<string>();
        var rows = new List<RouteRow>();

        foreach (var type in types)
        {
            if (type is null) continue;
            var typeName = type.FullName ?? type.Name;

            IList<CustomAttributeData> data;
            try
            {
                data = type.GetCustomAttributesData();
            }
            catch (Exception ex)
            {
                attributeReadFailures.Add(typeName + ": " + ex.GetType().Name + ": " + ex.Message);
                continue;
            }

            foreach (var attribute in data)
            {
                string? attributeFullName;
                string attributeSimpleName;
                try
                {
                    attributeFullName = attribute.AttributeType.FullName;
                    attributeSimpleName = attribute.AttributeType.Name;
                }
                catch (Exception ex)
                {
                    attributeReadFailures.Add(typeName + ": attribute type unreadable: "
                                              + ex.GetType().Name + ": " + ex.Message);
                    continue;
                }

                if (string.Equals(attributeFullName, RouteAttributeFullName, StringComparison.Ordinal))
                {
                    var template = attribute.ConstructorArguments.Count == 1
                        ? attribute.ConstructorArguments[0].Value as string
                        : null;
                    if (string.IsNullOrWhiteSpace(template))
                        attributeReadFailures.Add(typeName
                            + ": RouteAttribute without exactly one non-empty string template argument");
                    else
                        rows.Add(new RouteRow(template, typeName));
                }
                else if (string.Equals(attributeSimpleName, "RouteAttribute", StringComparison.Ordinal))
                {
                    foreign.Add(typeName + " carries " + (attributeFullName ?? attributeSimpleName));
                }
            }
        }

        var name = product.GetName();
        return new RouteCensus(
            name.Name ?? "",
            name.Version?.ToString() ?? "",
            types.Count(t => t != null),
            typeLoadFailures,
            attributeReadFailures,
            foreign,
            rows.OrderBy(r => r.Route, StringComparer.Ordinal)
                .ThenBy(r => r.TypeName, StringComparer.Ordinal).ToList());
    }

    // ── The module flags ───────────────────────────────────────────────────────────────────────

    /// <summary>What THIS test project was compiled against: the constants are inlined here at
    /// compile time, so these values describe the reference the test project saw, not the assembly
    /// the test host loaded.</summary>
    private static IReadOnlyDictionary<string, bool> CompiledModuleFlags() =>
        new Dictionary<string, bool>(StringComparer.Ordinal)
        {
            ["Community"] = BuildModules.Community,
            ["Premium"] = BuildModules.Premium,
            ["DevTools"] = BuildModules.DevTools,
            ["Portal"] = BuildModules.Portal,
            ["Operations"] = BuildModules.Operations,
            ["LiveMonitoring"] = BuildModules.LiveMonitoring,
            ["PerfReport"] = BuildModules.PerfReport,
        };

    /// <summary>What the LOADED product assembly says, read off its metadata. Null = the constant is
    /// missing or is not a literal bool, which is itself a failure.</summary>
    private static IReadOnlyDictionary<string, bool?> ProductModuleFlags()
    {
        var flags = new Dictionary<string, bool?>(StringComparer.Ordinal);
        foreach (var flagName in ModuleFlagNames)
        {
            var field = typeof(BuildModules).GetField(flagName, BindingFlags.Public | BindingFlags.Static);
            flags[flagName] = field is { IsLiteral: true } && field.GetRawConstantValue() is bool b ? b : null;
        }
        return flags;
    }

    /// <summary>
    /// The module flags this census reasons with, after the configuration has been proved
    /// trustworthy. Called FIRST by every fact that reasons with module flags, which is every fact
    /// except F0_the_census_reads_a_live_product_assembly_before_any_verdict (it reads routes only).
    /// One definition, not a copy per fact,
    /// so a fact added later either calls it or says at its own body why it does not.
    /// </summary>
    private sealed record ModuleContext(IReadOnlyDictionary<string, bool> Flags)
    {
        public bool IsCompiledIn(string group) =>
            group == CoreGroup || (Flags.TryGetValue(group, out var on) && on);

        public string Edition =>
            Flags["Community"] ? "community" : Flags["PerfReport"] ? "full+private" : "full";
    }

    private ModuleContext RequireModuleFlagsWithAFrozenExpectation()
    {
        var compiled = CompiledModuleFlags();
        var reflected = ProductModuleFlags();

        foreach (var flagName in ModuleFlagNames)
            _out.WriteLine($"BuildModules.{flagName}: product(reflected)={Show(reflected[flagName])} "
                         + $"test-project(inlined)={compiled[flagName]}");

        var disagreeing = ModuleFlagNames
            .Where(n => reflected[n] != compiled[n])
            .Select(n => $"{n}: product={Show(reflected[n])} test-project={compiled[n]}")
            .ToList();

        Assert.True(disagreeing.Count == 0,
            "THE PRODUCT ASSEMBLY AND THIS TEST PROJECT DISAGREE ABOUT WHICH MODULES ARE COMPILED IN, so "
            + "nothing this class reports is evidence about either of them. Disagreeing flags: "
            + string.Join("; ", disagreeing) + ". The product value is read off the SQLTriage.dll the "
            + "test host actually loaded; the test-project value was inlined when this test assembly "
            + "was compiled. bin/ carries the LAST profile built, so a test assembly and a product "
            + "assembly from two different builds land here. WHAT TO CHECK: that the test assembly and "
            + "the product assembly came from the same -p:SQLTriageProfile build (and the same "
            + "-p:SQLTriagePrivate value), by the timestamps and paths of both DLLs, before reading any "
            + "other result in this class.");

        var flags = ModuleFlagNames.ToDictionary(n => n, n => reflected[n]!.Value, StringComparer.Ordinal);

        var communityShape = !flags["Premium"] && !flags["DevTools"] && !flags["Portal"] && !flags["PerfReport"];
        var fullShape = flags["Premium"] && flags["DevTools"] && flags["Portal"]
                        && flags["Operations"] && flags["LiveMonitoring"];
        var holds = flags["Community"] ? communityShape : fullShape;

        Assert.True(holds,
            "THIS MODULE COMBINATION HAS NO FROZEN EXPECTATION, so this census refuses to report on it "
            + "rather than skip. Flags: " + string.Join(", ", ModuleFlagNames.Select(n => n + "=" + flags[n]))
            + ". The expectations were frozen for two shapes only: Community=true implies Premium, "
            + "DevTools, Portal and PerfReport are all false; Community=false implies Premium, DevTools, "
            + "Portal, Operations and LiveMonitoring are all true. WHAT TO CHECK: how this assembly was "
            + "built (which -p: properties reached buildprofile.targets), and whether a new profile shape "
            + "was introduced on purpose. A new shape is a decision about what that edition sells, and "
            + "this census has no approved answer for it yet.");

        return new ModuleContext(flags);
    }

    private static string Show(bool? value) => value.HasValue ? value.Value.ToString() : "MISSING-OR-NOT-A-BOOL-LITERAL";

    // ── Haystack control ───────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Asserted BEFORE any needle, by every fact that reads routes, which is every fact except
    /// F0_the_module_flags_are_read_off_the_product_and_agree_with_the_test_build (it reads module flags
    /// only). Every verdict below is vacuously green over an empty
    /// or unreadable assembly, so an empty haystack is a failure, never a pass.
    /// </summary>
    private RouteCensus RequireALiveHaystack()
    {
        var census = Census.Value;
        _out.WriteLine($"product assembly {census.AssemblySimpleName} {census.AssemblyVersion} at "
                     + Product.Location);
        _out.WriteLine($"types={census.TypeCount} route-rows={census.Rows.Count} "
                     + $"routed-types={census.Rows.Select(r => r.TypeName).Distinct().Count()} "
                     + $"type-load-failures={census.TypeLoadFailures.Count} "
                     + $"attribute-read-failures={census.AttributeReadFailures.Count} "
                     + $"foreign-RouteAttribute={census.ForeignRouteAttributes.Count}");

        Assert.True(census.AssemblySimpleName == "SQLTriage",
            "the assembly that owns BuildModules is named '" + census.AssemblySimpleName + "', not "
            + "SQLTriage. WHAT TO CHECK: whether BuildModules moved to another assembly; this census reads "
            + "routes from the assembly that owns it.");

        Assert.True(census.TypeCount > 1000,
            "the product assembly yielded only " + census.TypeCount + " loadable types; a real SQLTriage "
            + "build carries thousands. LIVENESS FLOOR, not a frozen count. WHAT TO CHECK: whether the "
            + "right assembly was loaded and whether type loading failed wholesale.");

        Assert.True(census.Rows.Count > 0,
            "the product assembly yielded ZERO RouteAttribute rows, so every fact in this class would pass "
            + "over nothing. WHAT TO CHECK: whether the attribute's full name is still "
            + RouteAttributeFullName + " and whether the attribute data could be read at all.");

        Assert.True(census.TypeLoadFailures.Count == 0,
            "types in the product assembly could not be loaded, and an unloadable type is invisible to "
            + "this census, so a route on it would be neither caught nor counted: "
            + string.Join(" | ", census.TypeLoadFailures) + ". WHAT TO CHECK: which dependency failed to "
            + "load in the test host.");

        Assert.True(census.AttributeReadFailures.Count == 0,
            "custom attribute data could not be read for these types, so their routes are unknown: "
            + string.Join(" | ", census.AttributeReadFailures) + ". WHAT TO CHECK: the named types and "
            + "the assemblies their attributes come from.");

        Assert.True(census.ForeignRouteAttributes.Count == 0,
            "types carry an attribute named RouteAttribute that is NOT " + RouteAttributeFullName
            + ": " + string.Join(" | ", census.ForeignRouteAttributes) + ". This census reads only the "
            + "Blazor attribute. WHAT TO CHECK: whether these types are routable by some other router, in "
            + "which case this census is blind to them.");

        return census;
    }

    // ── The approved table, validated before use ───────────────────────────────────────────────

    private static IReadOnlyDictionary<string, (string Group, string File)> ApprovedTable()
    {
        var duplicates = ApprovedRouteTable.GroupBy(r => r.Route, StringComparer.Ordinal)
            .Where(g => g.Count() > 1).Select(g => g.Key).OrderBy(s => s, StringComparer.Ordinal).ToList();
        Assert.True(duplicates.Count == 0,
            "the approved route table names these routes more than once, so their ownership is ambiguous: "
            + string.Join(", ", duplicates) + ". WHAT TO CHECK: which module each page belongs to.");

        var unknownGroups = ApprovedRouteTable.Where(r => !RouteGroups.Contains(r.Group, StringComparer.Ordinal))
            .Select(r => r.Route + " -> " + r.Group).ToList();
        Assert.True(unknownGroups.Count == 0,
            "the approved route table uses groups that are not Core or a BuildModules flag: "
            + string.Join(", ", unknownGroups) + ". WHAT TO CHECK: the group names against "
            + "Data/BuildModules.cs.");

        return ApprovedRouteTable.ToDictionary(r => r.Route, r => (r.Group, r.File), StringComparer.Ordinal);
    }

    private void Dump(string title, IEnumerable<string> lines)
    {
        var sorted = lines.OrderBy(s => s, StringComparer.Ordinal).ToList();
        _out.WriteLine($"{title} (n={sorted.Count}):");
        foreach (var line in sorted) _out.WriteLine("    " + line);
    }

    private static string QualifiedTypeNameOf(string razorFile) =>
        ProfileGateModel.QualifiedTypeNamesFromRemovedPages(new[] { razorFile }).Single();

    // ── F0: instrument controls ────────────────────────────────────────────────────────────────

    [Fact]
    public void F0_the_census_reads_a_live_product_assembly_before_any_verdict()
    {
        var census = RequireALiveHaystack();
        Dump("routes read from RouteAttribute metadata (route  type)",
             census.Rows.Select(r => r.Route + "  " + r.TypeName));
    }

    [Fact]
    public void F0_the_module_flags_are_read_off_the_product_and_agree_with_the_test_build()
    {
        var modules = RequireModuleFlagsWithAFrozenExpectation();
        _out.WriteLine("edition under test: " + modules.Edition);
        Dump("groups compiled into this build", RouteGroups.Where(modules.IsCompiledIn));
        Dump("groups compiled OUT of this build", RouteGroups.Where(g => !modules.IsCompiledIn(g)));
    }

    // ── F1: every present route has an owner ───────────────────────────────────────────────────

    /// <summary>How the NEXT new page is caught, in ANY profile: a route no group owns fails here.</summary>
    [Fact]
    public void F1_every_route_in_the_build_is_owned_by_a_group_in_the_approved_table()
    {
        var modules = RequireModuleFlagsWithAFrozenExpectation();
        var census = RequireALiveHaystack();
        var table = ApprovedTable();

        var unowned = census.Rows.Where(r => !table.ContainsKey(r.Route)).ToList();
        Dump("routes present in the " + modules.Edition + " build", census.Rows.Select(r => r.Route + "  " + r.TypeName));
        Dump("routes present and OWNED by no group", unowned.Select(r => r.Route + "  " + r.TypeName));

        Assert.True(unowned.Count == 0,
            string.Join(" ", unowned.Select(r =>
                "route " + r.Route + " (type " + r.TypeName + ") is routable in this build but appears in "
                + "no module group of the approved route table.")) + " WHAT TO CHECK: which module this "
            + "page belongs to, and whether buildprofile.targets removes it in every profile where that "
            + "module is off. Which edition sells a page is a ruling, not something to infer from which "
            + "group would make this test pass.");
    }

    /// <summary>
    /// The table records ownership by PAGE. If a route literal moved to a different page, the owner the
    /// table names is no longer the file that declares it, and every other verdict here would be
    /// reasoning about the wrong page.
    /// </summary>
    [Fact]
    public void F1_every_owned_route_is_declared_by_the_page_the_approved_table_names()
    {
        RequireModuleFlagsWithAFrozenExpectation();
        var census = RequireALiveHaystack();
        var table = ApprovedTable();

        var moved = census.Rows
            .Where(r => table.ContainsKey(r.Route))
            .Where(r => !string.Equals(QualifiedTypeNameOf(table[r.Route].File), r.TypeName, StringComparison.Ordinal))
            .ToList();
        Dump("owned routes declared by a different type than the table's file maps to",
             moved.Select(r => r.Route + "  declared-by=" + r.TypeName + "  table-file=" + table[r.Route].File));

        Assert.True(moved.Count == 0,
            string.Join(" ", moved.Select(r =>
                "route " + r.Route + " is declared by type " + r.TypeName + ", but the approved route table "
                + "records it as declared by " + table[r.Route].File + " (type "
                + QualifiedTypeNameOf(table[r.Route].File) + "), owned by " + table[r.Route].Group + "."))
            + " WHAT TO CHECK: whether the @page directive moved between files or the page was renamed, and "
            + "whether the page's module ownership moved with it.");
    }

    // ── F2: nothing ships whose module is compiled out ─────────────────────────────────────────

    [Fact]
    public void F2_no_route_is_present_whose_owning_module_is_compiled_out()
    {
        var modules = RequireModuleFlagsWithAFrozenExpectation();
        var census = RequireALiveHaystack();
        var table = ApprovedTable();

        var escaped = census.Rows
            .Where(r => table.TryGetValue(r.Route, out var owner) && !modules.IsCompiledIn(owner.Group))
            .ToList();
        Dump("routes present whose owning module is compiled OUT",
             escaped.Select(r => r.Route + "  " + r.TypeName + "  module=" + table[r.Route].Group));

        Assert.True(escaped.Count == 0,
            string.Join(" ", escaped.Select(r =>
            {
                var owner = table[r.Route];
                return "route " + r.Route + " (type " + r.TypeName + ") is routable in this build, but its "
                     + "module " + owner.Group + " is compiled out (BuildModules." + owner.Group + " == false). "
                     + "WHAT TO CHECK: whether " + owner.File + " is removed by the ItemGroup for "
                     + owner.Group + " in buildprofile.targets, and whether this page is meant to ship in the "
                     + modules.Edition + " edition.";
            })));
    }

    // ── F3: everything ships whose module is compiled in ───────────────────────────────────────

    [Fact]
    public void F3_every_route_whose_owning_module_is_compiled_in_is_present()
    {
        var modules = RequireModuleFlagsWithAFrozenExpectation();
        var census = RequireALiveHaystack();
        var table = ApprovedTable();

        var present = new HashSet<string>(census.Rows.Select(r => r.Route), StringComparer.Ordinal);
        var expected = ApprovedRouteTable.Where(r => modules.IsCompiledIn(r.Group)).ToList();
        var missing = expected.Where(r => !present.Contains(r.Route)).ToList();

        Dump("routes the approved table expects in the " + modules.Edition + " build",
             expected.Select(r => r.Route + "  " + r.Group));
        Dump("expected routes MISSING from the build", missing.Select(r => r.Route + "  " + r.Group + "  " + r.File));

        Assert.True(missing.Count == 0,
            string.Join(" ", missing.Select(r =>
                "route " + r.Route + " is owned by module " + r.Group + ", which is compiled into this "
                + modules.Edition + " build, but no type in the build declares it.")) + " WHAT TO CHECK: "
            + "first, whether this route's module group in the approved table was changed without a recorded "
            + "ruling (a retagged row makes a correct Content Remove look like a mistake); then "
            + "whether the page was deleted or renamed (its table file is named beside each route in the "
            + "test output), whether its @page directive is still that exact literal, and whether "
            + "buildprofile.targets Content-Removes it by mistake in a profile where its module is on.");
    }

    // ── F4: specimen controls ──────────────────────────────────────────────────────────────────

    /// <summary>
    /// ⚠ THESE ARE SPECIMEN CONTROLS, NOT THE GUARANTEE. The guarantee is F1-F3, which enumerate from
    /// the compiled assembly. Naming a handful of routes cannot prove a set; these only fail loudly
    /// when the instrument stops discriminating: blind to routes, reading route CONSTANTS as if they
    /// were routes, or collapsing a type that declares two routes into one.
    /// </summary>
    [Fact]
    public void F4_specimen_controls_discriminate_routes_from_constants_and_types_from_routes()
    {
        var modules = RequireModuleFlagsWithAFrozenExpectation();
        var census = RequireALiveHaystack();
        var present = new HashSet<string>(census.Rows.Select(r => r.Route), StringComparer.Ordinal);

        // SPECIMEN CONTROL, NOT THE GUARANTEE: two Core pages are present in every build.
        foreach (var everyBuild in new[] { "/settings", "/servers" })
        {
            var everyBuildRoutable = present.Contains(everyBuild);
            Assert.True(everyBuildRoutable,
                "SPECIMEN CONTROL, NOT THE GUARANTEE: " + everyBuild + " is a Core page and must be routable "
                + "in every build, and it is absent from this " + modules.Edition + " build. WHAT TO CHECK: "
                + "whether the census is reading RouteAttribute data at all before believing any other result.");
        }

        // SPECIMEN CONTROL, NOT THE GUARANTEE: a route CONSTANT is not a route.
        var routeConstants = Product.GetType("SQLTriage.Data.RouteConstants", throwOnError: false);
        Assert.True(routeConstants != null,
            "SPECIMEN CONTROL, NOT THE GUARANTEE: SQLTriage.Data.RouteConstants is not in the product "
            + "assembly, so the constants-are-not-routes control has no subject. WHAT TO CHECK: whether it "
            + "was renamed or moved; a control whose subject silently vanished reads exactly like a pass.");
        var sessionsConstants = routeConstants!
            .GetFields(BindingFlags.Public | BindingFlags.Static)
            .Where(f => f.IsLiteral && f.FieldType == typeof(string) && (string?)f.GetRawConstantValue() == "/sessions")
            .Select(f => f.Name).ToList();
        _out.WriteLine($"RouteConstants literal fields whose value is /sessions: [{string.Join(", ", sessionsConstants)}]; "
                     + $"/sessions routable={present.Contains("/sessions")}; LiveMonitoring={modules.Flags["LiveMonitoring"]}");
        Assert.True(sessionsConstants.Count > 0,
            "SPECIMEN CONTROL, NOT THE GUARANTEE: no const string field on RouteConstants has the value "
            + "/sessions in this build, so this control can no longer show that a route CONSTANT is not "
            + "read as a route. WHAT TO CHECK: whether that constant was fenced or renamed, and whether "
            + "any other unfenced route constant still names a page that is compiled out of community.");
        var sessionsRoutable = present.Contains("/sessions");
        if (!modules.Flags["LiveMonitoring"])
            Assert.True(!sessionsRoutable,
                "SPECIMEN CONTROL, NOT THE GUARANTEE: LiveMonitoring is compiled out, the constant "
                + "RouteConstants." + sessionsConstants[0] + " = /sessions is in the assembly, and /sessions "
                + "was reported as a ROUTE. Either the census is reading string constants rather than "
                + "RouteAttribute metadata, or Pages/Sessions.razor shipped. WHAT TO CHECK: the declaring "
                + "type printed for /sessions in F0's output.");
        else
            Assert.True(sessionsRoutable,
                "SPECIMEN CONTROL, NOT THE GUARANTEE: LiveMonitoring is compiled in and /sessions is not "
                + "routable. WHAT TO CHECK: Pages/Sessions.razor and its @page directives.");

        // SPECIMEN CONTROL, NOT THE GUARANTEE: a census of TYPES is not a census of ROUTES.
        var multiRouteTypes = census.Rows.GroupBy(r => r.TypeName, StringComparer.Ordinal)
            .Where(g => g.Count() > 1).Select(g => g.Key).OrderBy(s => s, StringComparer.Ordinal).ToList();
        _out.WriteLine($"routed types declaring more than one route: [{string.Join(", ", multiRouteTypes)}]");
        foreach (var name in new[] { "SQLTriage.Pages.Pmemory", "SQLTriage.Pages.Sessions" })
        {
            var typePresent = Product.GetType(name, throwOnError: false) != null;
            _out.WriteLine($"    {name} present={typePresent}");
            Assert.True(typePresent == modules.Flags["LiveMonitoring"],
                "SPECIMEN CONTROL, NOT THE GUARANTEE: type " + name + " present=" + typePresent + " while "
                + "LiveMonitoring=" + modules.Flags["LiveMonitoring"] + ". WHAT TO CHECK: whether the page was "
                + "renamed (the two-route control names it) or whether its module gate changed.");
        }
        var expectedMultiRoute = modules.Flags["LiveMonitoring"]
            ? new List<string> { "SQLTriage.Pages.Pmemory", "SQLTriage.Pages.Sessions" }
            : new List<string>();
        Assert.True(multiRouteTypes.SequenceEqual(expectedMultiRoute, StringComparer.Ordinal),
            "SPECIMEN CONTROL, NOT THE GUARANTEE: expected exactly [" + string.Join(", ", expectedMultiRoute)
            + "] to declare more than one route (Pmemory: /pmemory and /memory; Sessions: /sessions and "
            + "/dashboard/sessions, both LiveMonitoring pages), and measured [" + string.Join(", ", multiRouteTypes)
            + "]. If the two-route pages vanished while LiveMonitoring is on, the census may be collapsing "
            + "a type's routes into one. WHAT TO CHECK: the per-type route rows in F0's output, and the "
            + "@page directives of the named pages.");

        // SPECIMEN CONTROL, NOT THE GUARANTEE: the opt-in PerfReport page follows its flag both ways.
        Assert.True(present.Contains("/performance-report") == modules.Flags["PerfReport"],
            "SPECIMEN CONTROL, NOT THE GUARANTEE: /performance-report routable="
            + present.Contains("/performance-report") + " but BuildModules.PerfReport=" + modules.Flags["PerfReport"]
            + ". It must be present exactly when -p:SQLTriagePrivate=true built a non-community profile. "
            + "WHAT TO CHECK: the SQLTPerfReport ItemGroup in buildprofile.targets and how this build was invoked.");

        // SPECIMEN CONTROL, NOT THE GUARANTEE: a parameterised LiveMonitoring route follows its flag both ways.
        Assert.True(present.Contains("/dashboard/{DashboardId}") == modules.Flags["LiveMonitoring"],
            "SPECIMEN CONTROL, NOT THE GUARANTEE: /dashboard/{DashboardId} routable="
            + present.Contains("/dashboard/{DashboardId}") + " but BuildModules.LiveMonitoring="
            + modules.Flags["LiveMonitoring"] + ". WHAT TO CHECK: Pages/Dashboard.razor and the "
            + "live-monitoring ItemGroup in buildprofile.targets.");
    }

    // ── F5: the full-profile predictor ─────────────────────────────────────────────────────────

    /// <summary>
    /// So that a page escaping COMMUNITY is also caught by a FULL-profile run, which is the run a
    /// developer makes locally.
    ///
    /// <para>⚠ THIS IS A MODEL OF MSBUILD ITEM EVALUATION — a tripwire over the buildprofile.targets
    /// XML, NOT THE GUARANTEE. It predicts which routed types a community build keeps by asking
    /// <see cref="ProfileGateModel"/> which <c>.razor</c> files the community profile Content-Removes,
    /// and mapping each file to a type by Razor's folder-to-namespace convention. MSBuild's real
    /// evaluation can differ from that model (a condition the model does not parse, an
    /// <c>@namespace</c> override, an item removed by a mechanism other than this file). The GUARANTEE
    /// is <see cref="F2_no_route_is_present_whose_owning_module_is_compiled_out"/> run in a real
    /// community build, which CI runs on pushes to main and on pull requests.</para>
    ///
    /// <para>In a community build this still runs, predicting only over the types present.</para>
    /// </summary>
    [Fact]
    public void F5_a_full_build_predicts_the_community_route_set_the_table_approves()
    {
        var modules = RequireModuleFlagsWithAFrozenExpectation();
        var census = RequireALiveHaystack();
        var table = ApprovedTable();
        var root = RawPassedScan.RepoRoot();

        var surface = ProfileGateModel.CommunitySurface(root);
        var removedTypes = new HashSet<string>(
            ProfileGateModel.QualifiedTypeNamesFromRemovedPages(surface.RemovedPages), StringComparer.Ordinal);
        Dump("MODEL: .razor files the community profile Content-Removes", surface.RemovedPages);

        // MODEL SPECIMEN CONTROLS, NOT THE GUARANTEE, both ways.
        Assert.True(removedTypes.Contains("SQLTriage.Pages.Sessions"),
            "MODEL SPECIMEN CONTROL, NOT THE GUARANTEE: the model of buildprofile.targets does not remove "
            + "SQLTriage.Pages.Sessions from a community build, but live-monitoring is off in community. "
            + "The model has stopped reading the item tree, so its prediction below is worthless. WHAT TO "
            + "CHECK: ProfileGateModel.CommunitySurface against the live-monitoring ItemGroup.");
        Assert.True(!removedTypes.Contains("SQLTriage.Pages.Settings"),
            "MODEL SPECIMEN CONTROL, NOT THE GUARANTEE: the model removes SQLTriage.Pages.Settings, a Core "
            + "page, from community. The model is over-removing, so its prediction below is worthless. "
            + "WHAT TO CHECK: ProfileGateModel's condition parsing against buildprofile.targets.");

        // The model's evaluated module switches for community.
        var evaluation = ProfileGateModel.Evaluate(root, new Dictionary<string, string>
        {
            ["SQLTriageProfile"] = "community",
            ["SQLTriagePrivate"] = "",
        });
        bool ModelTurnsOn(string excludeProperty) =>
            !(evaluation.Properties.TryGetValue(excludeProperty, out var v)
              && string.Equals(v, "true", StringComparison.OrdinalIgnoreCase));
        var modelOperationsOn = ModelTurnsOn("SQLTExcludeOperations");
        var modelLiveMonitoringOn = ModelTurnsOn("SQLTExcludeLiveMonitoring");
        _out.WriteLine($"MODEL community module switches: Operations={modelOperationsOn} LiveMonitoring={modelLiveMonitoringOn}");

        if (modules.Flags["Community"])
        {
            // In a real community build the model's switches can be checked against the real ones.
            Assert.True(modelOperationsOn == modules.Flags["Operations"]
                        && modelLiveMonitoringOn == modules.Flags["LiveMonitoring"],
                "MODEL CONTROL: the model of buildprofile.targets evaluates community as Operations="
                + modelOperationsOn + " LiveMonitoring=" + modelLiveMonitoringOn + ", but this real community "
                + "build carries BuildModules.Operations=" + modules.Flags["Operations"]
                + " LiveMonitoring=" + modules.Flags["LiveMonitoring"] + ". WHAT TO CHECK: buildprofile.json's "
                + "module toggles against what ProfileGateModel.Evaluate reads from it.");
        }

        // Every routed type must map to exactly one .razor file by the folder-to-namespace convention,
        // or the model cannot say whether that type is removed.
        var razorByType = RazorFilesByQualifiedTypeName(root);
        var routedTypes = census.Rows.Select(r => r.TypeName).Distinct(StringComparer.Ordinal).ToList();
        var unmapped = routedTypes
            .Where(t => !razorByType.TryGetValue(t, out var files) || files.Count != 1)
            .Select(t => t + " -> [" + string.Join(", ", razorByType.TryGetValue(t, out var files) ? files : new List<string>()) + "]")
            .ToList();
        Dump("routed types that do not map to exactly one .razor file", unmapped);
        Assert.True(unmapped.Count == 0,
            "these routed types do not map to exactly one .razor file under the folder-to-namespace "
            + "convention, so the model cannot predict whether a community build keeps them: "
            + string.Join(" | ", unmapped) + ". WHAT TO CHECK: an @namespace override in the page, a page "
            + "declared outside a .razor file, or two files that map to one type name.");

        var approvedCommunity = new HashSet<string>(
            ApprovedRouteTable
                .Where(r => r.Group == CoreGroup
                            || (r.Group == "Operations" && modelOperationsOn)
                            || (r.Group == "LiveMonitoring" && modelLiveMonitoringOn))
                .Select(r => r.Route),
            StringComparer.Ordinal);
        var predictedRows = census.Rows.Where(r => !removedTypes.Contains(r.TypeName)).ToList();
        var predicted = new HashSet<string>(predictedRows.Select(r => r.Route), StringComparer.Ordinal);

        Dump("MODEL: community route set predicted from this " + modules.Edition + " build",
             predictedRows.Select(r => r.Route + "  " + r.TypeName));
        Dump("APPROVED: community route set from the table", approvedCommunity);

        var wouldEscape = predictedRows.Where(r => !approvedCommunity.Contains(r.Route)).ToList();
        var wouldVanish = approvedCommunity.Where(r => !predicted.Contains(r)).ToList();
        Dump("predicted in community but NOT approved", wouldEscape.Select(r => r.Route + "  " + r.TypeName));
        Dump("approved for community but NOT predicted", wouldVanish);

        Assert.True(wouldEscape.Count == 0 && wouldVanish.Count == 0,
            string.Join(" ", wouldEscape.Select(r =>
            {
                if (!table.TryGetValue(r.Route, out var owner))
                    return "route " + r.Route + " (type " + r.TypeName + ") would ship in a community build "
                         + "according to the model of buildprofile.targets, and appears in no module group of "
                         + "the approved route table (F1 reports the same route). WHAT TO CHECK: which module "
                         + "this page belongs to, and whether buildprofile.targets removes it in every profile "
                         + "where that module is off.";
                return "route " + r.Route + " (type " + r.TypeName + ") would ship in a community build "
                     + "according to the model of buildprofile.targets, but the approved route table assigns "
                     + "it to " + owner.Group + ", which community compiles out. WHAT TO CHECK: whether "
                     + owner.File + " is removed by the ItemGroup for " + owner.Group + " in "
                     + "buildprofile.targets, and whether this page is meant to ship in the community edition.";
            }))
            + string.Join(" ", wouldVanish.Select(route =>
                " route " + route + " is approved for the community edition, but the model of "
                + "buildprofile.targets predicts no type in this build keeps it. WHAT TO CHECK: first, whether "
                + "this route's module group in the approved table was changed without a recorded ruling (a "
                + "retagged row makes a correct Content Remove look like a mistake); then whether its "
                + "page is Content-Removed by a community ItemGroup by mistake, or renamed or deleted."))
            + " (This verdict is a MODEL; the guarantee is F2 in a real community build.)");
    }

    /// <summary>
    /// Every <c>.razor</c> file in the app tree, keyed by the type name Razor generates for it. Skips
    /// the test tree and build output (<c>bin</c>, <c>obj</c>) and dot-directories, where copies of the
    /// app's markup are staged for other tests and would otherwise make every page map to two files.
    /// It walks DISK, not git's tracked list, deliberately: MSBuild's default Razor item glob reads disk
    /// too, so an untracked page MSBuild would compile is seen here, and a stray untracked copy of a
    /// routed page makes its type map to two files, which F5 fails on by name.
    /// </summary>
    private static IReadOnlyDictionary<string, List<string>> RazorFilesByQualifiedTypeName(DirectoryInfo root)
    {
        var byType = new Dictionary<string, List<string>>(StringComparer.Ordinal);
        var pending = new Stack<DirectoryInfo>();
        pending.Push(root);
        while (pending.Count > 0)
        {
            var dir = pending.Pop();
            foreach (var sub in dir.EnumerateDirectories())
            {
                var n = sub.Name;
                if (n.StartsWith(".", StringComparison.Ordinal)) continue;
                if (string.Equals(n, "bin", StringComparison.OrdinalIgnoreCase)) continue;
                if (string.Equals(n, "obj", StringComparison.OrdinalIgnoreCase)) continue;
                if (string.Equals(n, "node_modules", StringComparison.OrdinalIgnoreCase)) continue;
                if (dir.FullName == root.FullName && string.Equals(n, "Tests", StringComparison.OrdinalIgnoreCase)) continue;
                pending.Push(sub);
            }
            foreach (var file in dir.EnumerateFiles("*.razor"))
            {
                var rel = ProfileGateModel.Rel(root, file.FullName);
                var typeName = QualifiedTypeNameOf(rel);
                if (!byType.TryGetValue(typeName, out var list)) byType[typeName] = list = new List<string>();
                list.Add(rel);
            }
        }
        return byType;
    }
}
