; SQLTriage — Inno Setup installer script
; Requires Inno Setup 6.x (https://jrsoftware.org/isinfo.php)
;
; Build instructions:
;   1. Run from project root:
;        dotnet publish SQLTriage.csproj -c Release -r win-x64 -o publish\win-x64
;   2. Open this .iss in Inno Setup Compiler and click Build > Compile
;      OR run headless:  "C:\GitHub\Inno Setup 6\iscc.exe" installer\SQLTriage.iss
;
; The compiled Setup EXE lands in: release\SQLTriage-vX.Y.Z-buildNNNN-Setup.exe

#define AppName      "SQLTriage"
#define AppShortName "SQLTriage"
#define AppPublisher "Adrian Sullivan"
#define AppURL       "https://sqladrian.github.io/SQLTriage/"
#define AppExeName   "SQLTriage.exe"
; SourceDir / OutputDir can be overridden from the command line (CI):
;   iscc.exe /DSourceDir=... /DOutputDir=... installer\SQLTriage.iss
; Local default mirrors the publish path used by `dotnet publish ... -o publish\win-x64`.
#ifndef SourceDir
  #define SourceDir "..\publish\win-x64"
#endif
#ifndef OutputDir
  #define OutputDir "..\release"
#endif
; EditionSuffix distinguishes installer filenames per build profile, e.g.
; "-community" for public/community builds: iscc.exe /DEditionSuffix=-community ...
; Empty (full/private) keeps the historical filename.
#ifndef EditionSuffix
  #define EditionSuffix ""
#endif

; version.iss is auto-generated by the csproj BuildInstaller target before iscc runs.
; It defines AppVersion and BuildNumber.
#include "version.iss"

[Setup]
AppId={{A7F3C2D1-4E8B-4F9A-B3C7-1D2E5F6A8B9C}
AppName={#AppName}
AppVersion={#AppVersion}.{#BuildNumber}
AppVerName={#AppName} v{#AppVersion} (Build {#BuildNumber})
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL=https://github.com/SQLAdrian/SQLTriage/issues
AppUpdatesURL={#AppURL}
DefaultDirName={autopf}\{#AppShortName}
DefaultGroupName={#AppName}
AllowNoIcons=yes
; Per-user install — no UAC prompt (DBAs often lack admin on their workstation)
; User can override to machine-wide via the dialog
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir={#OutputDir}
OutputBaseFilename=SQLTriage-v{#AppVersion}-build{#BuildNumber}{#EditionSuffix}-Setup
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
SetupIconFile=assets\app.ico
WizardSmallImageFile=assets\wizard-small.bmp
WizardImageFile=assets\wizard-banner.bmp
; Wizard accept page — user must scroll and accept before installation proceeds.
; Path is relative to this .iss file (installer\ subdirectory).
LicenseFile=..\LICENSE.txt
UninstallDisplayIcon={app}\{#AppExeName}
UninstallDisplayName={#AppName}
VersionInfoVersion={#AppVersion}.{#BuildNumber}
VersionInfoCompany={#AppPublisher}
VersionInfoDescription=Free SQL Server monitoring for Windows DBAs
VersionInfoCopyright=Copyright (C) 2024-2026 {#AppPublisher}
MinVersion=10.0.17763

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Components]
Name: "main";        Description: "{#AppName} (required)";          Types: full compact custom; Flags: fixed
Name: "desktopicon"; Description: "Desktop shortcut";                Types: full
Name: "autostart";   Description: "Start with Windows (current user)"; Types: full

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional shortcuts:"; Components: desktopicon

[Files]
; ── Core application ─────────────────────────────────────────────────────
Source: "{#SourceDir}\{#AppExeName}"; DestDir: "{app}"; Flags: ignoreversion

; ── Licence — top-level so auditors and Programs-and-Features can read it ─
Source: "{#SourceDir}\LICENSE.txt"; DestDir: "{app}"; Flags: ignoreversion

; ── Config files — preserve user edits on upgrade ────────────────────────
;
; WHERE THE SOURCES LIVE, CHANGED 2026-09-10 (lane customer-update-path, DECISIONS ruling). The
; publish payload no longer puts operator-editable config in config\. It puts it in config.default\,
; and the app creates the real file in config\ on first run only when it is missing
; (Data\Services\ConfigDefaultsSeeder). The reason is the OTHER update route: an operator extracting
; the release zip over their install, which is what the customer update path had always actually been,
; and which no flag in this file can protect. Now the artefact itself cannot destroy their tuning,
; whatever route it arrives by.
;
; THE FLAGS BELOW ARE UNCHANGED AND MUST STAY THAT WAY. onlyifdoesntexist plus the CurStepChanged
; backup/restore in [Code] is what protects the Inno upgrade path specifically; the seeder protects the
; zip path. They are two nets over two different routes, not a duplication - an Inno upgrade never
; reaches the seeder, because the file is already there by the time the app first runs.
;
; version.json always overwritten (update check URL, whatsnew text) - a build artefact, not operator
; state, and a stale one makes the service misreport its own build (2026-08-03).
Source: "{#SourceDir}\config\version.json";              DestDir: "{app}\Config"; Flags: ignoreversion
; These are installed once; user customisations survive upgrades
Source: "{#SourceDir}\config.default\appsettings.json";          DestDir: "{app}\Config"; Flags: onlyifdoesntexist
Source: "{#SourceDir}\config.default\appsettings.Production.json"; DestDir: "{app}\Config"; Flags: onlyifdoesntexist
Source: "{#SourceDir}\config.default\dashboard-config.json";     DestDir: "{app}\Config"; Flags: onlyifdoesntexist
Source: "{#SourceDir}\config.default\alert-definitions.json";    DestDir: "{app}\Config"; Flags: onlyifdoesntexist
; sql-alerts-detailed.json removed 2026-08-26 (honesty-hunt alerts-r2-03, ruling 06:53 #6): it was
; verbatim competitor research (SolarWinds/Redgate/IDERA notes) that NO code path read, shipped into
; every client's Config\ folder. Deleted from the source tree, this [Files] line, OperatorConfigNames()
; below, and .handoff/.publicallow. Proved no reader before removal (whole-repo grep, re-run at delete).
Source: "{#SourceDir}\config.default\scheduled-tasks.json";      DestDir: "{app}\Config"; Flags: onlyifdoesntexist
; onlyifdoesntexist stays (ruling 2026-08-23 #4): the operator's edits must survive an upgrade.
; The cost of that is a config that never receives NEW shipped entries, so the app closes the
; gap instead - ScriptConfigurationMigrator adds any missing shipped entry at load, without
; touching anything already in the file. Do not switch this to ignoreversion.
Source: "{#SourceDir}\config.default\script-configurations.json"; DestDir: "{app}\Config"; Flags: onlyifdoesntexist
; ADDED 2026-09-10. PowerEstimateService.cs:225 reads Config\power-pricing.json off disk and its own
; comment at :44 says it is "editable per deployment" - so it is operator state by the same test as the
; six above. It had no entry in this file at all, and no TargetPath in the csproj either, so it reached
; the config folder by accident and an Inno upgrade would have re-laid the shipped defaults over an
; operator's tariff. Found while classifying the payload for the config.default split.
Source: "{#SourceDir}\config.default\power-pricing.json";        DestDir: "{app}\Config"; Flags: onlyifdoesntexist
; sql-checks.json was retired in commit 100965c — entry removed.

; ── The shipped defaults themselves ──────────────────────────────────────
; Delivered alongside, unguarded and always refreshed. Two jobs: an operator who DELETED a config file
; gets the CURRENT default back on the next start rather than nothing, and the folder is the one place
; a DBA can read what the shipped value actually was before they changed it. ConfigDefaultsSeeder only
; ever creates what is missing, so refreshing this folder can never reach anything in Config\.
; Unguarded like scripts\ and Assets\: nothing removes it from any build profile, so if the publish
; tree ever loses it, iscc aborts loudly instead of silently shipping an installer whose seeder has
; nothing to seed from.
Source: "{#SourceDir}\config.default\*"; DestDir: "{app}\config.default"; \
  Flags: ignoreversion recursesubdirs createallsubdirs

; ── Free-tier bundle — decrypted at boot with zero-key; no customer action needed ─
; ignoreversion: the Free check catalogue is regenerated with every build, so it is a product artefact
; that must be refreshed. It is in config\, NOT config.default\, for exactly that reason - seeding it
; first-run-only would freeze a customer's Free catalogue at their install date for ever.
Source: "{#SourceDir}\config\free-bundle.dat"; DestDir: "{app}\Config"; Flags: ignoreversion

; NOT SHIPPED BY THIS INSTALLER, deliberately (2026-09-10): the payload also carries
; Install-SQLTriage.ps1, the script that updates a SERVICE install in place from an extracted release.
; An Inno-installed client updates by running the next Setup.exe, so handing them a service-update
; script would offer a second, wrong procedure for their situation - it would stop at "service not
; found" and tell them nothing useful. The zip route is where that script belongs; the csproj ships it
; there. Recorded here rather than left silent, because an unnamed omission is how docs\ went two
; months without an update rule.

; ── Deploy scripts (database setup) ──────────────────────────────────────
; UNBUNDLED 2026-07-21 (client safety; see SQLTriage.csproj): the PerformanceMonitor_db /
; SQLWATCH_db payloads are the only Deploy\ contents and are excluded from the publish output,
; so publish\...\Deploy is normally ABSENT. Emit this entry only when the folder is actually
; present — otherwise iscc aborts the whole installer with "No files found matching ...\Deploy\*".
; If an opt-in Deploy payload is ever restored (csproj exclusion removed), it ships again with no
; further change here.
#if DirExists(AddBackslash(SourceDir) + "Deploy")
Source: "{#SourceDir}\Deploy\*"; DestDir: "{app}\Deploy"; \
  Flags: ignoreversion recursesubdirs createallsubdirs
#endif

; ── BP Scripts ────────────────────────────────────────────────────
; 2026-09-11, lane bpscripts-operator-edits-are-lost. THERE IS NO {app}\BPScripts SOURCE LINE HERE ANY
; MORE, and that is deliberate rather than an omission - the same move the compliance pack made a day
; earlier. Pages\BestPractice.razor:87 gives the operator a Save Script button, but it edits the
; CONTENT of a script already in the folder (Data\BPScriptService.cs:67-71 writes it straight into
; <install>\BPScripts) - it cannot create a file under a new name. The FILENAMES in that folder are
; still the operator's, by a different route: they drop a .sql file in by hand and run Sync
; Scripts from Folder (BestPractice.razor:41, BPScriptService.cs:73), which adopts it. A file this
; installer does not lay down is a file the pre-upgrade uninstall below cannot delete, and a folder
; no route delivers is a folder no route can copy over.
;
; The stock scripts install to {app}\BPScripts.default, which nobody authors in and every route may
; overwrite, and Data\Services\ConfigDefaultsSeeder creates {app}\BPScripts\<file> on the app's first
; run, per file, only when it is missing. BackupOperatorBPScripts in [Code] covers the ONE remaining
; window - upgrading from a build whose own uninstall log still carries {app}\BPScripts\*.
;
; The #if DirExists guard MOVES WITH THE FOLDER: buildprofile.targets:170-171 still removes
; BPScripts\** (the SOURCE glob) from a COMMUNITY publish, so BPScripts.default is legitimately
; absent there. Unguarded, this line aborted the whole compile with "No files found matching
; ..." and iscc returned 2, and the public release script caught that and quietly degraded the
; community release to zip-only. Measured 2026-08-24 against a community stub tree: exit 2,
; "Error on line 123". The guard is what lets a community installer exist at all.
#if DirExists(AddBackslash(SourceDir) + "BPScripts.default")
Source: "{#SourceDir}\BPScripts.default\*"; DestDir: "{app}\BPScripts.default"; \
  Flags: ignoreversion recursesubdirs createallsubdirs
#endif

; ── Diagnostic scripts (sp_Blitz, sp_PerfCheck, sp_ineachdb, sp_triage, ...) ──
; DiagnosticScriptRunner loads scripts\<ScriptPath> for every Full Audit entry. Without this line
; an installed build has no scripts\ folder at all and every entry fails with "Script not found".
; MISSING SINCE THE INSTALLER WAS INTRODUCED (e6e12e7) - proved 2026-08-24 by compiling this file
; against a stub tree that DID contain scripts\sp_Blitz.sql and finding no scripts\ in the
; installed image. ScriptCensusTests carries the text tripwire for it.
;
; DELIBERATELY UNGUARDED, unlike Deploy\ and BPScripts.default\ above. Those two are legitimately absent in
; some profile, so a guard is the only way they can compile. scripts\ is present in EVERY profile -
; SQLTriage.csproj:551-566 copies its six .sql files with no Condition, and only
; scripts\identity_manifest.sql is portal-gated. So an unguarded line is the loud tripwire: if the
; publish tree ever loses the folder, iscc aborts instead of silently shipping the broken installer
; this comment exists to describe. Do not "tidy" a #if DirExists onto it.
;
; THAT REASONING IS ENFORCED, NOT REMEMBERED. It was read from source, so on its own it is a belief,
; and if it is ever wrong this line aborts the community compile and the release silently degrades
; to zip-only again - the exact failure the guard above just fixed. ScriptCensusTests
; .Nothing_gates_the_scripts_folder_out_of_any_build_profile reads buildprofile.targets and the
; csproj and goes red the moment a profile starts removing scripts\ or a copy rule gains a
; Condition, naming this line as what will break.
Source: "{#SourceDir}\scripts\*"; DestDir: "{app}\scripts"; \
  Flags: ignoreversion recursesubdirs createallsubdirs

; ── wwwroot (Blazor static assets) ───────────────────────────────────────
Source: "{#SourceDir}\wwwroot\*"; DestDir: "{app}\wwwroot"; \
  Flags: ignoreversion recursesubdirs createallsubdirs

; ── Assets (brand mark for generated PDFs) ───────────────────────────────
; AssessmentPdf.cs loads Assets\brand\sqltriage-mark.png at render time (AppContext.BaseDirectory
; \Assets\brand\...). MISSING SINCE THE INSTALLER WAS INTRODUCED - every Inno-installed client got
; unbranded PDFs (the ⛁ glyph fallback), while the in-app UI stayed branded off wwwroot\images.
; SQLTriage.csproj:406 copies the asset to publish output with NO Condition and buildprofile.targets
; removes nothing under Assets\, so the folder is present in EVERY profile. DELIBERATELY UNGUARDED
; for the same reason scripts\ is: if the publish tree ever loses it, iscc aborts loudly instead of
; silently shipping unbranded PDFs. ScriptCensusTests covers it via FoldersTheRuntimeResolves.
Source: "{#SourceDir}\Assets\*"; DestDir: "{app}\Assets"; \
  Flags: ignoreversion recursesubdirs createallsubdirs

; ── Compliance pack (incident-response runbook and its companions) ───────
; Pages\AuditLogViewer.razor points the operator at docs/compliance/incident-response-runbook.md
; from FOUR banners (chain break, provenance indeterminate, unverifiable, and the break detail
; panel), and AuditLogService's chain-verification report body names the same file in its
; "Scope of this report" footer. There was no docs entry in this file from the day the installer
; was introduced to 2026-08-28: grep -ci docs SQLTriage.iss returned 0, so every Inno-installed
; client was told to consult a file that had never been placed on their machine - at the exact
; moment the app had just declared their audit chain broken. Found independently by honesty-hunt
; strings-r1-13. The runbook is written FOR the operator ({{primary-oncall}} placeholders, SOC2
; CC7.x mapping), not for us, so the fix is to deliver it rather than to delete the pointer.
;
; The whole folder, not just the runbook: the runbook sends the reader on to sign-off-log.md at
; four separate steps, and access-review-procedure.md and vendor-dependency-register.md do the
; same, so shipping one file would close one dangling pointer and leave four.
;
; DELIBERATELY UNGUARDED, like scripts\ and Assets\ above and unlike Deploy\ and BPScripts.default\.
; Nothing removes docs\ in any build profile (buildprofile.targets has no Content Remove under
; docs\), so the folder is present in every profile and an unguarded line aborts the compile
; loudly if that ever stops being true. DocPointerDeliveryTests is the text tripwire.
;
; SOURCE AND DESTINATION BOTH CHANGED 2026-09-10 (round two of lane customer-update-path), and the
; flag with them. This line used to copy the pack straight into {app}\docs\compliance with
; ignoreversion, which overwrote the operator's copy on EVERY upgrade. The four documents are theirs:
; sign-off-log.md calls itself a running evidence record, filled in append-only, that auditors will
; read, and two of the others carry {{placeholder}} values the buyer replaces before their first
; audit. Refreshing them destroyed a signed compliance record.
;
; They now follow the config.default rule exactly. The pristine templates are installed to
; {app}\docs.default\compliance, which nobody authors in and every route may overwrite, and
; Data\Services\ConfigDefaultsSeeder creates {app}\docs\compliance\<file> on the app's first run,
; per file, only when it is missing. That is why there is no {app}\docs Source line here any more,
; and it is deliberate rather than an omission: a file this installer does not lay down is a file the
; pre-upgrade uninstall below cannot delete. BackupOperatorDocs in [Code] covers the ONE remaining
; window - upgrading from a build whose own uninstall log still carries {app}\docs\compliance.
Source: "{#SourceDir}\docs.default\compliance\*"; DestDir: "{app}\docs.default\compliance"; \
  Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#AppName}";               Filename: "{app}\{#AppExeName}"
Name: "{group}\Uninstall {#AppName}";     Filename: "{uninstallexe}"
Name: "{autodesktop}\{#AppName}";         Filename: "{app}\{#AppExeName}"; Tasks: desktopicon

[Registry]
; Autostart — current user only, no admin required
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; \
  ValueType: string; ValueName: "{#AppName}"; \
  ValueData: """{app}\{#AppExeName}"""; \
  Flags: uninsdeletevalue; Components: autostart

[Run]
; "Launch now" on the final wizard page
Filename: "{app}\{#AppExeName}"; \
  Description: "{cm:LaunchProgram,{#AppName}}"; \
  Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Remove logs on uninstall (cache/config in %APPDATA% are left — user data)
Type: filesandordirs; Name: "{app}\logs"

[Code]
// ── Upgrade detection ─────────────────────────────────────────────────────
function GetUninstallString(): String;
var
  sUnInstPath: String;
  sUnInstallString: String;
begin
  sUnInstPath := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\{#SetupSetting("AppId")}_is1');
  sUnInstallString := '';
  if not RegQueryStringValue(HKLM, sUnInstPath, 'UninstallString', sUnInstallString) then
    RegQueryStringValue(HKCU, sUnInstPath, 'UninstallString', sUnInstallString);
  Result := sUnInstallString;
end;

function IsUpgrade(): Boolean;
begin
  Result := (GetUninstallString() <> '');
end;

// ── Operator-owned config preservation across an upgrade ───────────────────
// The Config\*.json files shipped 'onlyifdoesntexist' (see [Files]) carry operator data: the admin
// credential (AdminAuth Hash/Salt in appsettings.json) and the update kill-switch (Updates:Enabled).
// CurStepChanged below runs the PREVIOUS version's uninstaller silently BEFORE the new [Files] copy,
// and that uninstaller deletes every file recorded in its own uninstall log - which includes these.
// The 'onlyifdoesntexist' guard then finds them absent and re-lays the shipped default, wiping the
// operator's data on EVERY upgrade (honesty-hunt platform-r1-02, #2 in the wave top-ten).
//
// This also covers upgrading FROM a build that predates this fix: that build's uninstall log still
// carries the files, so uninsneveruninstall on the NEW [Files] entries alone would NOT save them on
// the very next upgrade. Backing them up before the uninstall and restoring them after keeps the
// 2026-08-23 #4 ruling's promise on the exact path it was written for, whatever the old build did.
// The list below must stay in step with the 'onlyifdoesntexist' Config entries in [Files]
// (ScriptCensusTests.Operator_owned_config_survives_the_pre_upgrade_uninstall is the tripwire).
function OperatorConfigNames(): TArrayOfString;
begin
  SetArrayLength(Result, 7);
  Result[0] := 'appsettings.json';
  Result[1] := 'appsettings.Production.json';
  Result[2] := 'dashboard-config.json';
  Result[3] := 'alert-definitions.json';
  Result[4] := 'scheduled-tasks.json';
  Result[5] := 'script-configurations.json';
  // Added 2026-09-10 with its [Files] entry: PowerEstimateService reads it off disk and its own
  // comment calls it editable per deployment, so it is operator state and the uninstall would eat it.
  Result[6] := 'power-pricing.json';
end;

procedure BackupOperatorConfig(const BackupDir: String);
var
  Names: TArrayOfString;
  i: Integer;
  ConfigDir, Src, Dst: String;
begin
  ConfigDir := ExpandConstant('{app}\Config');
  Names := OperatorConfigNames();
  ForceDirectories(BackupDir);
  for i := 0 to GetArrayLength(Names) - 1 do
  begin
    Src := ConfigDir + '\' + Names[i];
    if FileExists(Src) then
    begin
      Dst := BackupDir + '\' + Names[i];
      FileCopy(Src, Dst, False);
    end;
  end;
end;

procedure RestoreOperatorConfig(const BackupDir: String);
var
  Names: TArrayOfString;
  i: Integer;
  ConfigDir, Src, Dst: String;
begin
  ConfigDir := ExpandConstant('{app}\Config');
  Names := OperatorConfigNames();
  ForceDirectories(ConfigDir);
  for i := 0 to GetArrayLength(Names) - 1 do
  begin
    Src := BackupDir + '\' + Names[i];
    Dst := ConfigDir + '\' + Names[i];
    // Only restore what the uninstaller actually removed; never clobber a file that survived.
    if FileExists(Src) and (not FileExists(Dst)) then
      FileCopy(Src, Dst, False);
  end;
end;

// ── The operator's compliance pack, across the same uninstall ──────────────
// Added 2026-09-10 (round two of lane customer-update-path). docs\compliance holds four documents the
// OPERATOR fills in - sign-off-log.md is an append-only evidence record auditors read - and until this
// lane [Files] laid them down with ignoreversion, so every upgrade replaced them with blank templates.
// They are no longer installed by [Files] at all (the pack ships to {app}\docs.default\compliance and
// the app seeds the real one when it is missing), which removes them from the uninstall log going
// forward.
//
// This covers the one window that leaves: upgrading FROM a build that predates the change, whose own
// uninstall log still names {app}\docs\compliance\*.md, and whose uninstaller therefore deletes them.
// Same shape and same reasoning as BackupOperatorConfig above; the difference is that this folder has
// no fixed name list, so it enumerates what is actually there.
procedure BackupOperatorDocs(const BackupDir: String);
var
  FindRec: TFindRec;
  DocsDir: String;
begin
  DocsDir := ExpandConstant('{app}\docs\compliance');
  if not DirExists(DocsDir) then
    exit;
  ForceDirectories(BackupDir);
  if FindFirst(DocsDir + '\*.md', FindRec) then
  begin
    try
      repeat
        if FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY = 0 then
          FileCopy(DocsDir + '\' + FindRec.Name, BackupDir + '\' + FindRec.Name, False);
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;
end;

procedure RestoreOperatorDocs(const BackupDir: String);
var
  FindRec: TFindRec;
  DocsDir: String;
begin
  if not DirExists(BackupDir) then
    exit;
  DocsDir := ExpandConstant('{app}\docs\compliance');
  ForceDirectories(DocsDir);
  if FindFirst(BackupDir + '\*.md', FindRec) then
  begin
    try
      repeat
        // Only restore what the uninstaller actually removed; never clobber a file that survived.
        if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY = 0)
           and (not FileExists(DocsDir + '\' + FindRec.Name)) then
          FileCopy(BackupDir + '\' + FindRec.Name, DocsDir + '\' + FindRec.Name, False);
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;
end;

// ── The operator's Best Practice scripts, across the same uninstall ────────
// Added 2026-09-11 (lane bpscripts-operator-edits-are-lost). Until this lane [Files] laid
// {app}\BPScripts\* down with ignoreversion, so every upgrade replaced a script the operator had
// edited in the app with our stock copy. They no longer ship there at all, which removes them from
// the uninstall log going forward.
//
// THIS COVERS THE WINDOW THAT LEAVES, AND WITHOUT IT THE FIX WOULD BE WORSE THAN THE DEFECT ON THIS
// ONE ROUTE: upgrading FROM any build that predates the change, whose own uninstall log still names
// {app}\BPScripts\*, whose uninstaller therefore deletes the operator's scripts - and nothing
// re-lays them now, because the seeder only creates what BPScripts.default\ carries. Same shape as
// BackupOperatorDocs above; like it, the folder has no fixed name list. Save Script only edits the
// CONTENT of a script already there; the operator NAMES these files by a different route - they
// drop a .sql file in by hand and run Sync Scripts from Folder (BestPractice.razor:41,
// BPScriptService.cs:73), which adopts it - so this enumerates what is actually there.
procedure BackupOperatorBPScripts(const BackupDir: String);
var
  FindRec: TFindRec;
  ScriptsDir: String;
begin
  ScriptsDir := ExpandConstant('{app}\BPScripts');
  if not DirExists(ScriptsDir) then
    exit;
  ForceDirectories(BackupDir);
  if FindFirst(ScriptsDir + '\*', FindRec) then
  begin
    try
      repeat
        if FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY = 0 then
          FileCopy(ScriptsDir + '\' + FindRec.Name, BackupDir + '\' + FindRec.Name, False);
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;
end;

procedure RestoreOperatorBPScripts(const BackupDir: String);
var
  FindRec: TFindRec;
  ScriptsDir: String;
begin
  if not DirExists(BackupDir) then
    exit;
  ScriptsDir := ExpandConstant('{app}\BPScripts');
  ForceDirectories(ScriptsDir);
  if FindFirst(BackupDir + '\*', FindRec) then
  begin
    try
      repeat
        // Only restore what the uninstaller actually removed; never clobber a file that survived.
        if (FindRec.Attributes and FILE_ATTRIBUTE_DIRECTORY = 0)
           and (not FileExists(ScriptsDir + '\' + FindRec.Name)) then
          FileCopy(BackupDir + '\' + FindRec.Name, ScriptsDir + '\' + FindRec.Name, False);
      until not FindNext(FindRec);
    finally
      FindClose(FindRec);
    end;
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  sUnInstallString: String;
  iResultCode: Integer;
  BackupDir, DocsBackupDir, BPScriptsBackupDir: String;
begin
  if (CurStep = ssInstall) and IsUpgrade() then begin
    BackupDir := ExpandConstant('{tmp}\sqltriage-operator-config-backup');
    DocsBackupDir := ExpandConstant('{tmp}\sqltriage-operator-docs-backup');
    BPScriptsBackupDir := ExpandConstant('{tmp}\sqltriage-operator-bpscripts-backup');
    BackupOperatorConfig(BackupDir);
    BackupOperatorDocs(DocsBackupDir);
    BackupOperatorBPScripts(BPScriptsBackupDir);
    sUnInstallString := RemoveQuotes(GetUninstallString());
    Exec(sUnInstallString, '/SILENT /NORESTART /SUPPRESSMSGBOXES', '', SW_HIDE, ewWaitUntilTerminated, iResultCode);
    RestoreOperatorConfig(BackupDir);
    RestoreOperatorDocs(DocsBackupDir);
    RestoreOperatorBPScripts(BPScriptsBackupDir);
  end;
end;
