; SQLTriage — Inno Setup installer script
; Requires Inno Setup 6.x (https://jrsoftware.org/isinfo.php)
;
; Build instructions:
;   1. Run from project root:
;        dotnet publish SQLTriage.csproj -c Release -r win-x64 -o publish\win-x64
;   2. Open this .iss in Inno Setup Compiler and click Build > Compile
;      OR run headless:  "C:\GitHub\Inno Setup 6\iscc.exe" installer\SQLTriage.iss
;
; The compiled Setup EXE lands in: release\SQLTriage-vX.Y.Z-buildNNNN-Setup.exe

#define AppName      "SQLTriage"
#define AppShortName "SQLTriage"
#define AppPublisher "Adrian Sullivan"
#define AppURL       "https://sqladrian.github.io/SQLTriage/"
#define AppExeName   "SQLTriage.exe"
; SourceDir / OutputDir can be overridden from the command line (CI):
;   iscc.exe /DSourceDir=... /DOutputDir=... installer\SQLTriage.iss
; Local default mirrors the publish path used by `dotnet publish ... -o publish\win-x64`.
#ifndef SourceDir
  #define SourceDir "..\publish\win-x64"
#endif
#ifndef OutputDir
  #define OutputDir "..\release"
#endif
; EditionSuffix distinguishes installer filenames per build profile, e.g.
; "-community" for public/community builds: iscc.exe /DEditionSuffix=-community ...
; Empty (full/private) keeps the historical filename.
#ifndef EditionSuffix
  #define EditionSuffix ""
#endif

; version.iss is auto-generated by the csproj BuildInstaller target before iscc runs.
; It defines AppVersion and BuildNumber.
#include "version.iss"

[Setup]
AppId={{A7F3C2D1-4E8B-4F9A-B3C7-1D2E5F6A8B9C}
AppName={#AppName}
AppVersion={#AppVersion}.{#BuildNumber}
AppVerName={#AppName} v{#AppVersion} (Build {#BuildNumber})
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL=https://github.com/SQLAdrian/SQLTriage/issues
AppUpdatesURL={#AppURL}
DefaultDirName={autopf}\{#AppShortName}
DefaultGroupName={#AppName}
AllowNoIcons=yes
; Per-user install — no UAC prompt (DBAs often lack admin on their workstation)
; User can override to machine-wide via the dialog
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir={#OutputDir}
OutputBaseFilename=SQLTriage-v{#AppVersion}-build{#BuildNumber}{#EditionSuffix}-Setup
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
SetupIconFile=assets\app.ico
WizardSmallImageFile=assets\wizard-small.bmp
WizardImageFile=assets\wizard-banner.bmp
; Wizard accept page — user must scroll and accept before installation proceeds.
; Path is relative to this .iss file (installer\ subdirectory).
LicenseFile=..\LICENSE.txt
UninstallDisplayIcon={app}\{#AppExeName}
UninstallDisplayName={#AppName}
VersionInfoVersion={#AppVersion}.{#BuildNumber}
VersionInfoCompany={#AppPublisher}
VersionInfoDescription=Free SQL Server monitoring for Windows DBAs
VersionInfoCopyright=Copyright (C) 2024-2026 {#AppPublisher}
MinVersion=10.0.17763

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Components]
Name: "main";        Description: "{#AppName} (required)";          Types: full compact custom; Flags: fixed
Name: "desktopicon"; Description: "Desktop shortcut";                Types: full
Name: "autostart";   Description: "Start with Windows (current user)"; Types: full

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional shortcuts:"; Components: desktopicon

[Files]
; ── Core application ─────────────────────────────────────────────────────
Source: "{#SourceDir}\{#AppExeName}"; DestDir: "{app}"; Flags: ignoreversion

; ── Licence — top-level so auditors and Programs-and-Features can read it ─
Source: "{#SourceDir}\LICENSE.txt"; DestDir: "{app}"; Flags: ignoreversion

; ── Config files — preserve user edits on upgrade ────────────────────────
; version.json always overwritten (update check URL, whatsnew text)
Source: "{#SourceDir}\Config\version.json";              DestDir: "{app}\Config"; Flags: ignoreversion
; These are installed once; user customisations survive upgrades
Source: "{#SourceDir}\Config\appsettings.json";          DestDir: "{app}\Config"; Flags: onlyifdoesntexist
Source: "{#SourceDir}\Config\appsettings.Production.json"; DestDir: "{app}\Config"; Flags: onlyifdoesntexist
Source: "{#SourceDir}\Config\dashboard-config.json";     DestDir: "{app}\Config"; Flags: onlyifdoesntexist
Source: "{#SourceDir}\Config\alert-definitions.json";    DestDir: "{app}\Config"; Flags: onlyifdoesntexist
; sql-alerts-detailed.json removed 2026-08-26 (honesty-hunt alerts-r2-03, ruling 06:53 #6): it was
; verbatim competitor research (SolarWinds/Redgate/IDERA notes) that NO code path read, shipped into
; every client's Config\ folder. Deleted from the source tree, this [Files] line, OperatorConfigNames()
; below, and .handoff/.publicallow. Proved no reader before removal (whole-repo grep, re-run at delete).
Source: "{#SourceDir}\Config\scheduled-tasks.json";      DestDir: "{app}\Config"; Flags: onlyifdoesntexist
; onlyifdoesntexist stays (ruling 2026-08-23 #4): the operator's edits must survive an upgrade.
; The cost of that is a config that never receives NEW shipped entries, so the app closes the
; gap instead - ScriptConfigurationMigrator adds any missing shipped entry at load, without
; touching anything already in the file. Do not switch this to ignoreversion.
Source: "{#SourceDir}\Config\script-configurations.json"; DestDir: "{app}\Config"; Flags: onlyifdoesntexist
; sql-checks.json was retired in commit 100965c — entry removed.

; ── Free-tier bundle — decrypted at boot with zero-key; no customer action needed ─
Source: "{#SourceDir}\Config\free-bundle.dat"; DestDir: "{app}\Config"; Flags: ignoreversion

; ── Deploy scripts (database setup) ──────────────────────────────────────
; UNBUNDLED 2026-07-21 (client safety; see SQLTriage.csproj): the PerformanceMonitor_db /
; SQLWATCH_db payloads are the only Deploy\ contents and are excluded from the publish output,
; so publish\...\Deploy is normally ABSENT. Emit this entry only when the folder is actually
; present — otherwise iscc aborts the whole installer with "No files found matching ...\Deploy\*".
; If an opt-in Deploy payload is ever restored (csproj exclusion removed), it ships again with no
; further change here.
#if DirExists(AddBackslash(SourceDir) + "Deploy")
Source: "{#SourceDir}\Deploy\*"; DestDir: "{app}\Deploy"; \
  Flags: ignoreversion recursesubdirs createallsubdirs
#endif

; ── BP Scripts ────────────────────────────────────────────────────────────
; buildprofile.targets:158-167 removes BPScripts\** from a COMMUNITY publish, so the folder is
; legitimately absent there. Unguarded, this line aborted the whole compile with "No files found
; matching ...\BPScripts\*" and iscc returned 2; the public release script caught that and quietly
; degraded the community release to zip-only. Measured 2026-08-24 against a community stub tree:
; exit 2, "Error on line 123". The guard is what lets a community installer exist at all.
#if DirExists(AddBackslash(SourceDir) + "BPScripts")
Source: "{#SourceDir}\BPScripts\*"; DestDir: "{app}\BPScripts"; \
  Flags: ignoreversion recursesubdirs createallsubdirs
#endif

; ── Diagnostic scripts (sp_Blitz, sp_PerfCheck, sp_ineachdb, sp_triage, ...) ──
; DiagnosticScriptRunner loads scripts\<ScriptPath> for every Full Audit entry. Without this line
; an installed build has no scripts\ folder at all and every entry fails with "Script not found".
; MISSING SINCE THE INSTALLER WAS INTRODUCED (e6e12e7) - proved 2026-08-24 by compiling this file
; against a stub tree that DID contain scripts\sp_Blitz.sql and finding no scripts\ in the
; installed image. ScriptCensusTests carries the text tripwire for it.
;
; DELIBERATELY UNGUARDED, unlike Deploy\ and BPScripts\ above. Those two are legitimately absent in
; some profile, so a guard is the only way they can compile. scripts\ is present in EVERY profile -
; SQLTriage.csproj:551-566 copies its six .sql files with no Condition, and only
; scripts\identity_manifest.sql is portal-gated. So an unguarded line is the loud tripwire: if the
; publish tree ever loses the folder, iscc aborts instead of silently shipping the broken installer
; this comment exists to describe. Do not "tidy" a #if DirExists onto it.
;
; THAT REASONING IS ENFORCED, NOT REMEMBERED. It was read from source, so on its own it is a belief,
; and if it is ever wrong this line aborts the community compile and the release silently degrades
; to zip-only again - the exact failure the guard above just fixed. ScriptCensusTests
; .Nothing_gates_the_scripts_folder_out_of_any_build_profile reads buildprofile.targets and the
; csproj and goes red the moment a profile starts removing scripts\ or a copy rule gains a
; Condition, naming this line as what will break.
Source: "{#SourceDir}\scripts\*"; DestDir: "{app}\scripts"; \
  Flags: ignoreversion recursesubdirs createallsubdirs

; ── wwwroot (Blazor static assets) ───────────────────────────────────────
Source: "{#SourceDir}\wwwroot\*"; DestDir: "{app}\wwwroot"; \
  Flags: ignoreversion recursesubdirs createallsubdirs

; ── Assets (brand mark for generated PDFs) ───────────────────────────────
; AssessmentPdf.cs loads Assets\brand\sqltriage-mark.png at render time (AppContext.BaseDirectory
; \Assets\brand\...). MISSING SINCE THE INSTALLER WAS INTRODUCED - every Inno-installed client got
; unbranded PDFs (the ⛁ glyph fallback), while the in-app UI stayed branded off wwwroot\images.
; SQLTriage.csproj:406 copies the asset to publish output with NO Condition and buildprofile.targets
; removes nothing under Assets\, so the folder is present in EVERY profile. DELIBERATELY UNGUARDED
; for the same reason scripts\ is: if the publish tree ever loses it, iscc aborts loudly instead of
; silently shipping unbranded PDFs. ScriptCensusTests covers it via FoldersTheRuntimeResolves.
Source: "{#SourceDir}\Assets\*"; DestDir: "{app}\Assets"; \
  Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#AppName}";               Filename: "{app}\{#AppExeName}"
Name: "{group}\Uninstall {#AppName}";     Filename: "{uninstallexe}"
Name: "{autodesktop}\{#AppName}";         Filename: "{app}\{#AppExeName}"; Tasks: desktopicon

[Registry]
; Autostart — current user only, no admin required
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; \
  ValueType: string; ValueName: "{#AppName}"; \
  ValueData: """{app}\{#AppExeName}"""; \
  Flags: uninsdeletevalue; Components: autostart

[Run]
; "Launch now" on the final wizard page
Filename: "{app}\{#AppExeName}"; \
  Description: "{cm:LaunchProgram,{#AppName}}"; \
  Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Remove logs on uninstall (cache/config in %APPDATA% are left — user data)
Type: filesandordirs; Name: "{app}\logs"

[Code]
// ── Upgrade detection ─────────────────────────────────────────────────────
function GetUninstallString(): String;
var
  sUnInstPath: String;
  sUnInstallString: String;
begin
  sUnInstPath := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\{#SetupSetting("AppId")}_is1');
  sUnInstallString := '';
  if not RegQueryStringValue(HKLM, sUnInstPath, 'UninstallString', sUnInstallString) then
    RegQueryStringValue(HKCU, sUnInstPath, 'UninstallString', sUnInstallString);
  Result := sUnInstallString;
end;

function IsUpgrade(): Boolean;
begin
  Result := (GetUninstallString() <> '');
end;

// ── Operator-owned config preservation across an upgrade ───────────────────
// The Config\*.json files shipped 'onlyifdoesntexist' (see [Files]) carry operator data: the admin
// credential (AdminAuth Hash/Salt in appsettings.json) and the update kill-switch (Updates:Enabled).
// CurStepChanged below runs the PREVIOUS version's uninstaller silently BEFORE the new [Files] copy,
// and that uninstaller deletes every file recorded in its own uninstall log - which includes these.
// The 'onlyifdoesntexist' guard then finds them absent and re-lays the shipped default, wiping the
// operator's data on EVERY upgrade (honesty-hunt platform-r1-02, #2 in the wave top-ten).
//
// This also covers upgrading FROM a build that predates this fix: that build's uninstall log still
// carries the files, so uninsneveruninstall on the NEW [Files] entries alone would NOT save them on
// the very next upgrade. Backing them up before the uninstall and restoring them after keeps the
// 2026-08-23 #4 ruling's promise on the exact path it was written for, whatever the old build did.
// The list below must stay in step with the 'onlyifdoesntexist' Config entries in [Files]
// (ScriptCensusTests.Operator_owned_config_survives_the_pre_upgrade_uninstall is the tripwire).
function OperatorConfigNames(): TArrayOfString;
begin
  SetArrayLength(Result, 6);
  Result[0] := 'appsettings.json';
  Result[1] := 'appsettings.Production.json';
  Result[2] := 'dashboard-config.json';
  Result[3] := 'alert-definitions.json';
  Result[4] := 'scheduled-tasks.json';
  Result[5] := 'script-configurations.json';
end;

procedure BackupOperatorConfig(const BackupDir: String);
var
  Names: TArrayOfString;
  i: Integer;
  ConfigDir, Src, Dst: String;
begin
  ConfigDir := ExpandConstant('{app}\Config');
  Names := OperatorConfigNames();
  ForceDirectories(BackupDir);
  for i := 0 to GetArrayLength(Names) - 1 do
  begin
    Src := ConfigDir + '\' + Names[i];
    if FileExists(Src) then
    begin
      Dst := BackupDir + '\' + Names[i];
      FileCopy(Src, Dst, False);
    end;
  end;
end;

procedure RestoreOperatorConfig(const BackupDir: String);
var
  Names: TArrayOfString;
  i: Integer;
  ConfigDir, Src, Dst: String;
begin
  ConfigDir := ExpandConstant('{app}\Config');
  Names := OperatorConfigNames();
  ForceDirectories(ConfigDir);
  for i := 0 to GetArrayLength(Names) - 1 do
  begin
    Src := BackupDir + '\' + Names[i];
    Dst := ConfigDir + '\' + Names[i];
    // Only restore what the uninstaller actually removed; never clobber a file that survived.
    if FileExists(Src) and (not FileExists(Dst)) then
      FileCopy(Src, Dst, False);
  end;
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  sUnInstallString: String;
  iResultCode: Integer;
  BackupDir: String;
begin
  if (CurStep = ssInstall) and IsUpgrade() then begin
    BackupDir := ExpandConstant('{tmp}\sqltriage-operator-config-backup');
    BackupOperatorConfig(BackupDir);
    sUnInstallString := RemoveQuotes(GetUninstallString());
    Exec(sUnInstallString, '/SILENT /NORESTART /SUPPRESSMSGBOXES', '', SW_HIDE, ewWaitUntilTerminated, iResultCode);
    RestoreOperatorConfig(BackupDir);
  end;
end;
